# Generated by Django 4.2.5 on 2024-02-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='products_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('process', 'Processing'), ('Shipped', 'Shipped')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('disable', 'Disable'), ('draft', 'Draft')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='tags',
            name='responses',
            field=models.CharField(choices=[('3', '⭐⭐⭐'), ('1', '⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐')], default='⭐', max_length=1000000000),
        ),
    ]
