# Generated by Django 4.2.5 on 2024-02-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_cartorder_products_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='products_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('process', 'Processing'), ('Shipped', 'Shipped')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('disable', 'Disable'), ('published', 'Published')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_image', to='apps.product'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='responses',
            field=models.CharField(choices=[('4', '⭐⭐⭐⭐'), ('1', '⭐'), ('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='⭐', max_length=1000000000),
        ),
    ]
