# Generated by Django 4.2.5 on 2024-02-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_cartorder_products_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='products_status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('process', 'Processing'), ('delivered', 'Delivered')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('disable', 'Disable'), ('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='apps.product'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='responses',
            field=models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐'), ('4', '⭐⭐⭐⭐'), ('1', '⭐'), ('3', '⭐⭐⭐')], default='⭐', max_length=1000000000),
        ),
    ]
