# Generated by Django 4.2.5 on 2024-02-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_cartorder_products_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='products_status',
            field=models.CharField(choices=[('process', 'Processing'), ('delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_status',
            field=models.CharField(choices=[('disable', 'Disable'), ('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='tags',
            name='responses',
            field=models.CharField(choices=[('1', '⭐'), ('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐')], default='⭐', max_length=1000000000),
        ),
    ]
