# Generated by Django 4.2.5 on 2024-02-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_cartorder_products_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='products_status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('delivered', 'Delivered'), ('process', 'Processing')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Draft'), ('disable', 'Disable'), ('rejected', 'Rejected'), ('published', 'Published')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='tags',
            name='responses',
            field=models.CharField(choices=[('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐')], default='⭐', max_length=1000000000),
        ),
    ]
