# Generated by Django 4.2.5 on 2024-02-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_cartorder_products_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='products_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('Shipped', 'Shipped'), ('process', 'Processing')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review'), ('disable', 'Disable')], default='In_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='tags',
            name='responses',
            field=models.CharField(choices=[('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐')], default='⭐', max_length=1000000000),
        ),
    ]
